name: card_scanner
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_ml_kit: ^0.19.0
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  image_cropper: ^8.1.0
  path_provider: ^2.0.11 # To save files temporarily
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  shared_preferences: ^2.3.5
  uuid: ^4.5.1
  csv: ^6.0.0
  permission_handler: ^11.3.1
  flutter_file_dialog: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/linkedin.png
    - lib/assets/report.png
    - lib/assets/video.png
    - lib/assets/group.png
    - lib/assets/search.png
